import React from 'react';

const ChronoLogPrivacyPage = () => {
  return (
    <div>
      <h2>ChronoLog Privacy Policy</h2>

      <p>
        Privacy Policy: 
        <ul>
          <li>Data Collection and Use: All data generated by ChronoLog is stored locally on your device. We do not collect, store personal data externally or share it with third parties.</li>
          <li>Data Storage: All data is stored exclusively on your device, giving you full control over this data per the specifications and limitations of your device and operating system.</li>
          <li>Third-Party Providers: While ChronoLog currently does not integrate with any third-party providers that collect or process your data, we reserve the right to implement such services in the future to enhance user experience. Any such changes will be updated in this privacy policy.</li>
          <li>Changes to This Privacy Policy: We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</li>
          <li>Contact Us: If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us.</li>
        </ul>
      </p>
      <p>
        By using ChronoLog, you signify your acceptance of this Privacy Policy. If you do not agree to this policy, please do not use our app. Your continued use of ChronoLog following the posting of changes to this policy will be deemed your acceptance of those changes.
      </p>
      <p>
        This policy is effective as of 2023-08-03.
      </p>

    </div>
  );
};

export default ChronoLogPrivacyPage;
